<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CheckinSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('checkin')->insert([
            [
                'email' => 'andri.saputra@mail.com',
                'nama_lengkap' => 'Andri Saputra',
                'nik' => '3374101809910001',
                'instansi' => 'PT Cahaya Listrik Nusantara',
                'no_hp' => '081276543210',
                'bidang_tujuan' => 'Bidang Ketenagalistrikan',
                'keperluan' => 'Konsultasi teknis pemasangan jaringan listrik.',
                'foto_selfie' => null,
                'waktu_masuk' => now()->subHours(6),
                'id_bidang' => 5,
                'id_status' => 1,
            ],
            [
                'email' => 'dewi.anggraini@mail.com',
                'nama_lengkap' => 'Dewi Anggraini',
                'nik' => '3374102408940002',
                'instansi' => 'CV Surya Energi Mandiri',
                'no_hp' => '082134567890',
                'bidang_tujuan' => 'Bidang Energi Terbarukan',
                'keperluan' => 'Konsultasi pengembangan PLTS atap.',
                'foto_selfie' => null,
                'waktu_masuk' => now()->subHours(5),
                'id_bidang' => 3,
                'id_status' => 1,
            ],
            [
                'email' => 'fajar.pratama@mail.com',
                'nama_lengkap' => 'Fajar Pratama',
                'nik' => '3374100503920003',
                'instansi' => 'PT Bumi Tambang Sejahtera',
                'no_hp' => '085689012345',
                'bidang_tujuan' => 'Bidang Mineral dan Batubara',
                'keperluan' => 'Klarifikasi dokumen perizinan pertambangan.',
                'foto_selfie' => null,
                'waktu_masuk' => now()->subHours(4),
                'id_bidang' => 2,
                'id_status' => 1,
            ],
            [
                'email' => 'nisa.hakim@mail.com',
                'nama_lengkap' => 'Nisa Hakim',
                'nik' => '3374103009960004',
                'instansi' => 'PT Hemat Energi Indonesia',
                'no_hp' => '081392001122',
                'bidang_tujuan' => 'Bidang Konservasi Energi',
                'keperluan' => 'Pelaporan efisiensi energi industri.',
                'foto_selfie' => null,
                'waktu_masuk' => now()->subHours(4)->subMinutes(30),
                'id_bidang' => 4,
                'id_status' => 1,
            ],
            [
                'email' => 'rizky.pramana@mail.com',
                'nama_lengkap' => 'Rizky Pramana',
                'nik' => '3374101208900005',
                'instansi' => 'PT Energi Sejahtera',
                'no_hp' => '081345667788',
                'bidang_tujuan' => 'Bidang Ketenagalistrikan',
                'keperluan' => 'Permohonan rekomendasi teknis instalasi listrik.',
                'foto_selfie' => null,
                'waktu_masuk' => now()->subHours(3),
                'id_bidang' => 5,
                'id_status' => 1,
            ],
            [
                'email' => 'ayu.lestari@mail.com',
                'nama_lengkap' => 'Ayu Lestari',
                'nik' => '3374102107920006',
                'instansi' => 'CV Listrik Mandiri',
                'no_hp' => '082112233445',
                'bidang_tujuan' => 'Bidang Energi Terbarukan',
                'keperluan' => 'Pengajuan proposal energi surya.',
                'foto_selfie' => null,
                'waktu_masuk' => now()->subHours(3)->subMinutes(20),
                'id_bidang' => 3,
                'id_status' => 1,
            ],
            [
                'email' => 'yoga.prasetyo@mail.com',
                'nama_lengkap' => 'Yoga Prasetyo',
                'nik' => '3374100206890007',
                'instansi' => 'PT Tambang Jaya Abadi',
                'no_hp' => '085701234567',
                'bidang_tujuan' => 'Bidang Mineral dan Batubara',
                'keperluan' => 'Konsultasi teknis pengelolaan tambang.',
                'foto_selfie' => null,
                'waktu_masuk' => now()->subHours(2),
                'id_bidang' => 2,
                'id_status' => 1,
            ],
            [
                'email' => 'salsa.putri@mail.com',
                'nama_lengkap' => 'Salsa Putri',
                'nik' => '3374101109990008',
                'instansi' => 'PT Energi Hijau Lestari',
                'no_hp' => '081233344455',
                'bidang_tujuan' => 'Bidang Konservasi Energi',
                'keperluan' => 'Evaluasi program konservasi energi.',
                'foto_selfie' => null,
                'waktu_masuk' => now()->subHours(2)->subMinutes(15),
                'id_bidang' => 4,
                'id_status' => 1,
            ],
            [
                'email' => 'bagus.wicaksono@mail.com',
                'nama_lengkap' => 'Bagus Wicaksono',
                'nik' => '3374100905880009',
                'instansi' => 'PT Daya Listrik Utama',
                'no_hp' => '081267890123',
                'bidang_tujuan' => 'Bidang Ketenagalistrikan',
                'keperluan' => 'Koordinasi pemeliharaan jaringan listrik.',
                'foto_selfie' => null,
                'waktu_masuk' => now()->subHours(1),
                'id_bidang' => 5,
                'id_status' => 1,
            ],
            [
                'email' => 'fitri.nur@mail.com',
                'nama_lengkap' => 'Fitri Nur Aisyah',
                'nik' => '3374100709930010',
                'instansi' => 'CV Solar Mandiri',
                'no_hp' => '082245678901',
                'bidang_tujuan' => 'Bidang Energi Terbarukan',
                'keperluan' => 'Konsultasi perizinan PLTS.',
                'foto_selfie' => null,
                'waktu_masuk' => now()->subMinutes(55),
                'id_bidang' => 3,
                'id_status' => 1,
            ],
            [
                'email' => 'aldi.susanto@mail.com',
                'nama_lengkap' => 'Aldi Susanto',
                'nik' => '3374100608870011',
                'instansi' => 'PT Tambang Alam Raya',
                'no_hp' => '085612345678',
                'bidang_tujuan' => 'Bidang Mineral dan Batubara',
                'keperluan' => 'Klarifikasi laporan produksi tambang.',
                'foto_selfie' => null,
                'waktu_masuk' => now()->subMinutes(45),
                'id_bidang' => 2,
                'id_status' => 1,
            ],
            [
                'email' => 'intan.permata@mail.com',
                'nama_lengkap' => 'Intan Permata',
                'nik' => '3374102509950012',
                'instansi' => 'PT Energi Cerdas',
                'no_hp' => '081298761234',
                'bidang_tujuan' => 'Bidang Konservasi Energi',
                'keperluan' => 'Pelaporan audit energi gedung.',
                'foto_selfie' => null,
                'waktu_masuk' => now()->subMinutes(35),
                'id_bidang' => 4,
                'id_status' => 1,
            ],
            [
                'email' => 'rahmat.hidayat@mail.com',
                'nama_lengkap' => 'Rahmat Hidayat',
                'nik' => '3374101408910013',
                'instansi' => 'PT Arus Listrik Nasional',
                'no_hp' => '081377889900',
                'bidang_tujuan' => 'Bidang Ketenagalistrikan',
                'keperluan' => 'Permohonan rekomendasi teknis jaringan.',
                'foto_selfie' => null,
                'waktu_masuk' => now()->subMinutes(25),
                'id_bidang' => 5,
                'id_status' => 1,
            ],
            [
                'email' => 'melati.sari@mail.com',
                'nama_lengkap' => 'Melati Sari',
                'nik' => '3374102809960014',
                'instansi' => 'CV Energi Baru',
                'no_hp' => '082134556677',
                'bidang_tujuan' => 'Bidang Energi Terbarukan',
                'keperluan' => 'Pengajuan studi kelayakan energi terbarukan.',
                'foto_selfie' => null,
                'waktu_masuk' => now()->subMinutes(15),
                'id_bidang' => 3,
                'id_status' => 1,
            ],
            [
                'email' => 'hendra.kurniawan@mail.com',
                'nama_lengkap' => 'Hendra Kurniawan',
                'nik' => '3374100108900015',
                'instansi' => 'PT Batu Bara Jaya',
                'no_hp' => '085799988877',
                'bidang_tujuan' => 'Bidang Mineral dan Batubara',
                'keperluan' => 'Konsultasi teknis reklamasi tambang.',
                'foto_selfie' => null,
                'waktu_masuk' => now()->subMinutes(5),
                'id_bidang' => 2,
                'id_status' => 1,
            ],
        ]);
    }

}
